# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f9e900b8695cbdd1fd77b405d0e686e65939f3277d2804b98609f9db2a28455a3838c2f6817f756d5b0459fdb1ff317500d321a525f79473938d049d1850c12

test:
  secret_key_base: cdc471c2f6c4af72f10936b081a0a882352015aedce9d0abba4fcf0a27e1438161c9280f335cc1bd56289394f2f768d771d905aa16c7d5d339e68ab9ce658b17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
